services:
  db:
    container_name: db
    image: postgres:15.5-alpine3.18
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    networks:
      - default
  web:
    container_name: web
    build: .
    command: uv run python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
      POSTGRES_HOST: db
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - default
networks:
  default:
    driver: bridge
