services:
  db:
    image: mysql:8.0.42
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: mysql_admin
      MYSQL_PASSWORD: admin
    ports:
      - 3306:3306
    networks:
      - default_network
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./conf/mysql.cnf:/etc/mysql/my.cnf
    restart: always
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
  web:
    container_name: web
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    # command: uv run python manage.py runserver 0.0.0.0:8000
    # command: tail -f /dev/null
    volumes:
      - ..:/app
    environment:
      MYSQL_USER: mysql_admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: mydatabase
      MYSQL_HOST: db
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - default_network

volumes:
  mysql_data:

networks:
  default_network:
    driver: bridge
    name: default_network
